language: php

php:
  - 5.5

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - ls -l
  - phpunit --coverage-text --configuration Lamari/ReporterLBundle/phpunit.xml.dist
