language: php

php:
  - 5.5
  - 5.6
  
install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - phpunit --coverage-text --configuration $DBReporterL/Lamari/phpunit.xml.dist
